In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.10.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 2s 0us/step


In [3]:
print(x_train.shape,y_train.shape)

(60000, 28, 28) (60000,)


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.05026057,  0.24342728, -0.42287713,  0.5825881 ,  0.25002602,
        -0.1760692 ,  0.02838032, -0.48802754,  0.5194029 ,  0.45516643]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.08914658, 0.10814238, 0.05554226, 0.15180694, 0.10885834,
        0.0710904 , 0.08721721, 0.05203902, 0.14251174, 0.13364512]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.6438031

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2936 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1448 - accuracy: 0.9569
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1100 - accuracy: 0.9661
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0894 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0752 - accuracy: 0.9763


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0739 - accuracy: 0.9770 - 576ms/epoch - 2ms/step


[0.07385537773370743, 0.9769999980926514]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.4886468e-09, 5.8360530e-07, 8.3286767e-07, 4.0651069e-04,
        3.7883260e-10, 1.5875696e-07, 8.7008758e-13, 9.9958915e-01,
        3.2854609e-07, 2.5422587e-06],
       [9.4737604e-09, 3.6825746e-05, 9.9992657e-01, 3.0421354e-05,
        1.5321246e-12, 2.6355923e-07, 1.6706495e-07, 4.4684081e-13,
        5.8858568e-06, 4.5060709e-11],
       [1.6151563e-07, 9.9581581e-01, 1.1610626e-03, 1.4626735e-05,
        2.0619489e-05, 4.5134360e-07, 3.3376984e-06, 2.6894205e-03,
        2.9400698e-04, 3.9745936e-07],
       [9.9992156e-01, 3.4764667e-09, 2.7266033e-05, 5.8958017e-07,
        2.3388267e-07, 2.6740701e-05, 8.7999342e-06, 3.0035773e-07,
        7.3362187e-09, 1.4461546e-05],
       [1.0500271e-06, 1.2680271e-08, 6.2919219e-07, 4.7456519e-09,
        9.9984503e-01, 9.0941104e-09, 4.6751393e-07, 4.1833653e-05,
        1.9845179e-07, 1.1082103e-04]], dtype=float32)>

In [16]:
import shap

In [17]:
# Use the training data for deep explainer => can use fewer instances
explainer_ = shap.DeepExplainer(model, x_train)

keras is no longer supported, please use tf.keras instead.
Your TensorFlow version is newer than 2.4.0 and so graph support has been removed in eager mode and some static graphs may not be supported. See PR #1483 for discussion.
You have provided over 5k background samples! For better performance consider using smaller random sample.


In [ ]:
shap_values_ = explainer_.shap_values(x_test)

`tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
